apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9121"
    prometheus.io/scrape: "true"
    redis.opstreelabs.in: "true"
  labels:
    app: redis-master
    role: master
    release: redis
  name: redis-master
  namespace: default
spec:
  ports:
  - name: redis-exporter
    port: 9121
    protocol: TCP
    targetPort: 9121
  selector:
    app: redis-master
    role: master
