apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: redis-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Redis is the Schema for the redis API
      displayName: Redis
      kind: Redis
      name: redis.redis.redis.opstreelabs.in
      version: v1beta1
  description: redis-operator
  displayName: redis-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - redis-operator
  links:
  - name: Redis Operator
    url: https://redis-operator.domain
  maintainers:
  - email: zhang.arthur@gmail.com
    name: jimmy
  maturity: alpha
  provider:
    name: redis-operator
    url: https://github.com/OT-CONTAINER-KIT/redis-operator
  version: 0.0.0
